//SELECT VALUES

export const UserSelect = [
  '_id',
  'firstName',
  'lastName',
  'email',
  'university',
  'accountType',
  'privilegeLevel',
  'graduationYear',
  'department',
  'major',
  'phoneNumber',
  'work',
  'position',
  'bio',
  'links',
  'documents',
  'RSVPWebinars',
  'attendedWebinars',
  'connections',
  'pendingConnections',
  'joinedCommunities',
  'pendingCommunities',
  'broadcastedPosts',
  'communityPosts',
  'likes',
  'createdAt',
  'updatedAt',
];

export const CommunitySelect = [
  '_id',
  'name',
  'admin',
  'private',
  'members',
  'pendingMembers',
  'type',
  'description',
  'links',
  'documents',
  'university',
  'followedByCommunities',
  'followingCommunities',
  'outgoingPendingCommunityFollowRequests',
  'incomingPendingCommunityFollowRequests',
  'internalCurrentMemberPosts',
  'internalAlumniPosts',
  'externalPosts',
  'postsToOtherCommunities',
  'broadcastedPosts',
  'pinnedPosts',
  'scaleEventType',
  'createdAt',
  'updatedAt',
];

export const PostSelect = [
  '_id',
  'user',
  'message',
  'likes',
  'comments',
  'images',
  'toCommunity',
  'fromCommunity',
  'anonymous',
  'type',
  'university',
  'createdAt',
  'updatedAt',
];

export const CommunityEdgeSelect = [
  '_id',
  'from',
  'to',
  'accepted',
  'createdAt',
  'updatedAt',
];
