version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: node:14.4.0
    resource_class: xlarge

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/frontend/package.json" }}
            - v1-dependencies-

      ## run: npm test

      - run: cd client/frontend && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "client/frontend/package.json" }}

      - run: CI=false cd client/frontend && npm run build

      ## run: aws deploy
