version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: node:14.4.0
    resource_class: large ## Or xlarge

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/frontend/package.json" }}
            - v1-dependencies-

      ## run: npm test

      - run: cd client/frontend && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "client/frontend/package.json" }}

      - run: cd client/frontend && CI=false npm run build

      - persist_to_workspace:
          root: .
          paths:
            - .
      ## run: aws deploy

workflows:
  build-react:
    jobs:
      - build:
          filters:
            branches:
              only: master
